# Generated by Django 2.1.1 on 2018-10-17 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BanRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(auto_now=True, verbose_name='Дата и время добавления')),
                ('host', models.CharField(blank=True, max_length=255, verbose_name='Хост')),
                ('session', models.CharField(blank=True, max_length=255, verbose_name='Сессия')),
                ('view', models.CharField(max_length=255, verbose_name='Представление')),
                ('url', models.CharField(max_length=255, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Бан',
                'verbose_name_plural': 'Бан',
            },
        ),
        migrations.CreateModel(
            name='CheckRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_datetime', models.DateTimeField(auto_now=True, verbose_name='Дата и время проверки')),
                ('host', models.CharField(max_length=255, verbose_name='Хост')),
                ('session', models.CharField(max_length=255, verbose_name='Сессия')),
                ('view', models.CharField(max_length=255, verbose_name='Представление')),
                ('url', models.CharField(max_length=255, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Проверка запроса',
                'verbose_name_plural': 'Проверки запросов',
            },
        ),
    ]
