# Generated by Django 2.1.4 on 2018-12-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp_vue', '0007_auto_20181017_1037'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(related_name='users', to='cp_vue.CpRole'),
        ),
    ]
