# Generated by Django 2.1.4 on 2018-12-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('edit_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('mailer_lite_api_key', models.CharField(blank=True, max_length=255, verbose_name='Mailer Lite API key')),
                ('instagram', models.CharField(blank=True, max_length=255, verbose_name='Профиль в Instagram')),
                ('odnoklassniki', models.CharField(blank=True, max_length=255, verbose_name='Группа в Одноклассниках')),
                ('show_banner_on_main_page', models.BooleanField(default=False, verbose_name='Показывать на Главной странице баннер-растяжку вместо слайдера со спецпроектами')),
                ('copyright', models.TextField(blank=True, verbose_name='Копирайт')),
                ('yandex_count', models.TextField(blank=True, verbose_name='Код счетчика Yandex')),
                ('google_count', models.TextField(blank=True, verbose_name='Код счетчика Google')),
                ('meta_tags', models.TextField(blank=True, verbose_name='Дополнительные Мета-теги')),
                ('robots', models.TextField(blank=True, verbose_name='Содержимое файла robots.txt')),
                ('disable_site', models.BooleanField(default=False, verbose_name='Включить режим разработки')),
                ('disable_title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('disable_text', models.TextField(blank=True, verbose_name='Текст сообщения')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
