# Generated by Django 2.1.4 on 2019-02-19 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='show_banner_on_main_page',
        ),
    ]
