# Generated by Django 2.1.4 on 2019-02-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0002_remove_settings_show_banner_on_main_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='weather_data',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='weather_last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
