# Generated by Django 2.1.1 on 2021-09-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0003_auto_20190225_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='redaction_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес редакции'),
        ),
        migrations.AddField(
            model_name='settings',
            name='redaction_email',
            field=models.EmailField(blank=True, max_length=255, verbose_name='Email для общих вопросов'),
        ),
        migrations.AddField(
            model_name='settings',
            name='redaction_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Редакция'),
        ),
        migrations.AddField(
            model_name='settings',
            name='redaction_phone',
            field=models.CharField(blank=True, max_length=255, verbose_name='Телефон для общих вопросов'),
        ),
    ]
