# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 01:59
from __future__ import unicode_literals

import applications.mediafiles.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u0420\u0430\u0441\u0448\u0438\u0440\u0435\u043d\u0438\u0435',
                'verbose_name_plural': '\u0420\u0430\u0441\u0448\u0438\u0440\u0435\u043d\u0438\u044f',
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u0418\u043c\u044f \u0444\u0430\u0439\u043b\u0430 \u043e\u0440\u0438\u0433\u0438\u043d\u0430\u043b\u0430')),
                ('file', models.FileField(max_length=1000, upload_to=applications.mediafiles.models.get_file_path, verbose_name='\u0424\u0430\u0439\u043b')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='\u0428\u0438\u0440\u0438\u043d\u0430, px')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='\u0412\u044b\u0441\u043e\u0442\u0430, px')),
                ('file_size', models.IntegerField(verbose_name='\u0420\u0430\u0437\u043c\u0435\u0440 \u043e\u0440\u0438\u0433\u0438\u043d\u0430\u043b\u0430, \u041a\u0411')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0437\u0430\u0433\u0440\u0443\u0437\u043a\u0438')),
                ('is_active', models.BooleanField(default=True, verbose_name='\u0410\u043a\u0442\u0438\u0432\u043d\u044b\u0439')),
                ('extension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mediafiles.Extension', verbose_name='\u0420\u0430\u0441\u0448\u0438\u0440\u0435\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u041c\u0435\u0434\u0438\u0430\u0442\u0435\u043a\u0430',
                'verbose_name_plural': '\u041c\u0435\u0434\u0438\u0430\u0442\u0435\u043a\u0430',
            },
        ),
        migrations.CreateModel(
            name='MediaTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0442\u0435\u0433\u0430')),
                ('model', models.CharField(blank=True, max_length=255, verbose_name='\u041c\u043e\u0434\u0435\u043b\u044c')),
                ('is_default', models.BooleanField(default=False, verbose_name='\u0422\u0435\u0433 \u043f\u043e \u0443\u043c\u043e\u043b\u0447\u0430\u043d\u0438\u044e')),
            ],
            options={
                'verbose_name': '\u041c\u0435\u0434\u0438\u0430\u0442\u0435\u0433',
                'verbose_name_plural': '\u041c\u0435\u0434\u0438\u0430\u0442\u0435\u0433\u0438',
            },
        ),
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u0418\u043c\u044f \u0444\u0430\u0439\u043b\u0430')),
                ('suffix', models.CharField(max_length=255, verbose_name='\u0421\u0443\u0444\u0444\u0438\u043a\u0441')),
                ('file', models.FileField(max_length=1000, upload_to=applications.mediafiles.models.get_thumbnail_file_path, verbose_name='\u0424\u0430\u0439\u043b')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='\u0428\u0438\u0440\u0438\u043d\u0430, px')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='\u0412\u044b\u0441\u043e\u0442\u0430, px')),
                ('file_size', models.IntegerField(verbose_name='\u0420\u0430\u0437\u043c\u0435\u0440 \u043e\u0440\u0438\u0433\u0438\u043d\u0430\u043b\u0430, \u041a\u0411')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('original_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediafiles.MediaFile', verbose_name='\u041e\u0440\u0438\u0433\u0438\u043d\u0430\u043b')),
            ],
            options={
                'verbose_name': '\u041c\u0438\u043d\u0438\u0430\u0442\u044e\u0440\u0430',
                'verbose_name_plural': '\u041c\u0438\u043d\u0438\u0430\u0442\u044e\u0440\u044b',
            },
        ),
        migrations.AddField(
            model_name='mediafile',
            name='tags',
            field=models.ManyToManyField(blank=True, to='mediafiles.MediaTag', verbose_name='\u0422\u0435\u0433\u0438'),
        ),
    ]
