# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-02 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediafiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediafile',
            options={'verbose_name': '\u0413\u0430\u043b\u0435\u0440\u0435\u044f', 'verbose_name_plural': '\u0413\u0430\u043b\u0435\u0440\u0435\u044f'},
        ),
    ]
