# Generated by Django 2.1.4 on 2019-01-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='age_restriction',
            field=models.CharField(max_length=255, verbose_name='Возрастное ограничение'),
        ),
    ]
