# Generated by Django 2.1.4 on 2018-12-19 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filmsession',
            options={'ordering': ('session_time',), 'verbose_name': 'Сеанс', 'verbose_name_plural': 'Сеансы'},
        ),
        migrations.RenameField(
            model_name='filmsession',
            old_name='datetime',
            new_name='session_time',
        ),
    ]
