# Generated by Django 2.1.4 on 2018-12-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_auto_20181220_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special',
            name='codename',
            field=models.CharField(max_length=255, unique=True, verbose_name='URL (кодовое название)'),
        ),
    ]
