# Generated by Django 2.1.4 on 2018-12-19 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_auto_20181219_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='event',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report', to='root.Event', verbose_name='Анонс события'),
        ),
    ]
