# Generated by Django 2.1.4 on 2019-01-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_auto_20190128_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='publication_date',
        ),
        migrations.AlterField(
            model_name='slideritem',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Описание'),
        ),
    ]
