# Generated by Django 2.1.4 on 2019-01-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_auto_20190128_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='start_event_date',
        ),
        migrations.AlterField(
            model_name='slider',
            name='format',
            field=models.CharField(choices=[('format_3x2', 'Горизонтальный / 3:2'), ('format_2x1', 'Горизонтальный / 2:1')], max_length=45, verbose_name='Формат слайдера'),
        ),
    ]
