# Generated by Django 2.1.4 on 2018-12-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_auto_20181220_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='publication_date',
        ),
        migrations.AlterField(
            model_name='film',
            name='age_restriction',
            field=models.PositiveSmallIntegerField(verbose_name='Возрастное ограничение'),
        ),
        migrations.AlterField(
            model_name='film',
            name='duration',
            field=models.PositiveSmallIntegerField(verbose_name='Продолжительность, мин'),
        ),
        migrations.AlterField(
            model_name='film',
            name='release_year',
            field=models.PositiveSmallIntegerField(verbose_name='Год выпуска'),
        ),
    ]
