# Generated by Django 2.1.4 on 2018-12-20 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediafiles', '0003_auto_20181219_1051'),
        ('root', '0005_auto_20181220_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='SidebarBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('edit_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Состояние')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('link', models.CharField(max_length=255, verbose_name='Ссылка')),
                ('start_publication_date', models.DateTimeField(null=True, verbose_name='Дата и время начала публикации')),
                ('end_publication_date', models.DateTimeField(null=True, verbose_name='Дата и время окончания публикации')),
                ('comment', models.CharField(blank=True, default='', max_length=255, verbose_name='Комментарий')),
                ('cover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediafiles.MediaFile', verbose_name='Обложка')),
            ],
            options={
                'verbose_name': 'Баннер в сайдбаре',
                'verbose_name_plural': 'Баннеры в сайдбаре',
            },
        ),
        migrations.CreateModel(
            name='WideBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('edit_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Состояние')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('link', models.CharField(max_length=255, verbose_name='Ссылка')),
                ('start_publication_date', models.DateTimeField(null=True, verbose_name='Дата и время начала публикации')),
                ('end_publication_date', models.DateTimeField(null=True, verbose_name='Дата и время окончания публикации')),
                ('comment', models.CharField(blank=True, default='', max_length=255, verbose_name='Комментарий')),
                ('cover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediafiles.MediaFile', verbose_name='Обложка')),
            ],
            options={
                'verbose_name': 'Баннер-растяжка',
                'verbose_name_plural': 'Баннеры-растяжки',
            },
        ),
    ]
