# Generated by Django 2.1.4 on 2019-02-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0005_auto_20190129_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideritem',
            name='weight',
            field=models.PositiveIntegerField(default=0, verbose_name='Вес'),
        ),
    ]
