# Generated by Django 2.1.4 on 2019-02-07 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0006_slideritem_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryRubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('edit_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('name', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('comment', models.CharField(blank=True, default='', max_length=255, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Рубрика исторических статей',
                'verbose_name_plural': 'Рубрики исторических статей',
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='history',
            name='rubric',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='root.HistoryRubric', verbose_name='Рубрика'),
            preserve_default=False,
        ),
    ]
