# Generated by Django 2.1.4 on 2018-12-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0006_sidebarbanner_widebanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='placereview',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Комментарий'),
        ),
    ]
