# Generated by Django 2.1.4 on 2018-12-21 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0008_slider_slideritem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideritem',
            name='slider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='root.Slider', verbose_name='Слайдер'),
        ),
    ]
