# Generated by Django 2.1.4 on 2018-12-21 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0009_auto_20181221_1107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ('-id',), 'verbose_name': 'Слайдер', 'verbose_name_plural': 'Слайдеры'},
        ),
    ]
