# Generated by Django 2.1.4 on 2019-02-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0009_auto_20190213_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='contacts',
            field=models.CharField(blank=True, max_length=255, verbose_name='Контактная информация'),
        ),
        migrations.AddField(
            model_name='place',
            name='instagram',
            field=models.URLField(blank=True, max_length=255, verbose_name='Профиль в Instagram'),
        ),
        migrations.AddField(
            model_name='place',
            name='site',
            field=models.URLField(blank=True, max_length=255, verbose_name='Сайт'),
        ),
    ]
