# Generated by Django 2.1.4 on 2019-02-14 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediafiles', '0003_auto_20181219_1051'),
        ('root', '0010_auto_20190214_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebarbanner',
            name='horizontal_cover',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='horizontal_banners', to='mediafiles.MediaFile', verbose_name='Обложка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sidebarbanner',
            name='cover',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verticals_banners', to='mediafiles.MediaFile', verbose_name='Обложка'),
        ),
    ]
