# Generated by Django 2.1.4 on 2019-02-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0013_topitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topitem',
            name='content_type',
        ),
        migrations.AddField(
            model_name='topitem',
            name='codename',
            field=models.CharField(default='', max_length=255, verbose_name='Сущность'),
            preserve_default=False,
        ),
    ]
