# Generated by Django 2.1.4 on 2019-02-15 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0014_auto_20190215_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='topitem',
            name='weight',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topitem',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_items', to='contentblocks.Page', verbose_name='Страница'),
        ),
    ]
