# Generated by Django 2.1.4 on 2019-02-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0016_auto_20190219_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topitem',
            old_name='codename',
            new_name='entity',
        ),
        migrations.AddField(
            model_name='cityguide',
            name='guide_format',
            field=models.CharField(choices=[('hotel', 'Где остановиться?'), ('food', 'Где поесть?'), ('activities', 'Что посмотреть?')], default='', max_length=45, verbose_name='Форматы контента'),
            preserve_default=False,
        ),
    ]
