# Generated by Django 2.1.4 on 2019-02-19 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0018_auto_20190219_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cityguide',
            name='content_author',
        ),
        migrations.RemoveField(
            model_name='cityguide',
            name='cover_author',
        ),
        migrations.RemoveField(
            model_name='cityguide',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='cityguide',
            name='publication_date',
        ),
    ]
