# Generated by Django 2.1.4 on 2019-02-20 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0019_auto_20190219_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityguideitem',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mediafiles.MediaFile', verbose_name='Обложка'),
        ),
    ]
