# Generated by Django 2.1.4 on 2019-02-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0020_auto_20190220_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityguideitem',
            name='weight',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
