# Generated by Django 2.1.4 on 2019-02-21 11:13

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0021_cityguideitem_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityguide',
            name='search_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cityguide',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='search_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True),
        ),
        migrations.AddField(
            model_name='history',
            name='search_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='history',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True),
        ),
        migrations.AddField(
            model_name='news',
            name='search_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='news',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True),
        ),
        migrations.AddField(
            model_name='person',
            name='search_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='person',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True),
        ),
        migrations.AddField(
            model_name='place',
            name='search_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='place',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='search_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True),
        ),
        migrations.AddField(
            model_name='special',
            name='search_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='special',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True),
        ),
        migrations.AlterField(
            model_name='cityguide',
            name='guide_format',
            field=models.CharField(choices=[('hotel', 'Где остановиться?'), ('food', 'Где поесть?'), ('activities', 'Что посмотреть?'), ('transport', 'Как перемещаться по городу?'), ('phones', 'Полезные телефоны')], max_length=45, verbose_name='Форматы контента'),
        ),
    ]
