# Generated by Django 2.1.4 on 2019-02-21 14:30

from django.db import migrations
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0022_auto_20190221_1113'),
    ]

    operations = [
        migrations.RunSQL("""   
            create text search configuration public.ru_fts(copy=russian);
            ALTER TEXT SEARCH CONFIGURATION ru_fts DROP MAPPING FOR word;
            ALTER TEXT SEARCH CONFIGURATION ru_fts ADD MAPPING FOR word WITH russian_stem;
            ALTER DATABASE %s SET default_text_search_config='ru_fts';
            set default_text_search_config = 'ru_fts';
            
            /* +++++++++++++++++++++++++++++++ */
            
            CREATE TRIGGER tsvectorupdate
            BEFORE INSERT OR UPDATE
            ON root_news
            FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger(search_vector, 'public.ru_fts', "search_text");
            
            CREATE INDEX root_news_search_vector
            ON root_news USING GIST (search_vector);
            
            UPDATE root_news SET edit_date=NOW();
            
            /* +++++++++++++++++++++++++++++++ */
                         
            CREATE TRIGGER tsvectorupdate
            BEFORE INSERT OR UPDATE
            ON root_event
            FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger(search_vector, 'public.ru_fts', "search_text");
            
            CREATE INDEX root_event_search_vector
            ON root_event USING GIST (search_vector);
            
            UPDATE root_event SET edit_date=NOW();
            
            /* +++++++++++++++++++++++++++++++ */
                         
            CREATE TRIGGER tsvectorupdate
            BEFORE INSERT OR UPDATE
            ON root_report
            FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger(search_vector, 'public.ru_fts', "search_text");
            
            CREATE INDEX root_report_search_vector
            ON root_report USING GIST (search_vector);
            
            UPDATE root_report SET edit_date=NOW();
            
            /* +++++++++++++++++++++++++++++++ */
                         
            CREATE TRIGGER tsvectorupdate
            BEFORE INSERT OR UPDATE
            ON root_history
            FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger(search_vector, 'public.ru_fts', "search_text");
            
            CREATE INDEX root_history_search_vector
            ON root_history USING GIST (search_vector);
            
            UPDATE root_history SET edit_date=NOW();
            
            /* +++++++++++++++++++++++++++++++ */
                         
            CREATE TRIGGER tsvectorupdate
            BEFORE INSERT OR UPDATE
            ON root_place
            FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger(search_vector, 'public.ru_fts', "search_text");
            
            CREATE INDEX root_place_search_vector
            ON root_place USING GIST (search_vector);
            
            UPDATE root_place SET edit_date=NOW();
            
            /* +++++++++++++++++++++++++++++++ */
                         
            CREATE TRIGGER tsvectorupdate
            BEFORE INSERT OR UPDATE
            ON root_cityguide
            FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger(search_vector, 'public.ru_fts', "title", "search_text");
            
            CREATE INDEX root_cityguide_search_vector
            ON root_cityguide USING GIST (search_vector);
            
            UPDATE root_cityguide SET edit_date=NOW();
            
            /* +++++++++++++++++++++++++++++++ */
                         
            CREATE TRIGGER tsvectorupdate
            BEFORE INSERT OR UPDATE
            ON root_person
            FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger(search_vector, 'public.ru_fts', "search_text");
            
            CREATE INDEX root_person_search_vector
            ON root_person USING GIST (search_vector);
            
            UPDATE root_person SET edit_date=NOW();

            /* +++++++++++++++++++++++++++++++ */
                         
            CREATE TRIGGER tsvectorupdate
            BEFORE INSERT OR UPDATE
            ON root_special
            FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger(search_vector, 'public.ru_fts', "title", "search_text");
            
            CREATE INDEX root_special_search_vector
            ON root_special USING GIST (search_vector);
            
            UPDATE root_special SET edit_date=NOW();
                               

           """ % settings.DATABASES.get('default', dict()).get('NAME', '')
        )
    ]
