# Generated by Django 2.1.4 on 2019-02-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20190222_1130'),
        ('root', '0024_cityguide_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='attachment',
        ),
        migrations.AddField(
            model_name='feedback',
            name='attachments',
            field=models.ManyToManyField(to='files.UserFile', verbose_name='Файлы'),
        ),
    ]
