# Generated by Django 2.1.4 on 2019-02-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0025_auto_20190222_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='descriptor',
            field=models.CharField(default='', max_length=255, verbose_name='Подзаголовок'),
            preserve_default=False,
        ),
    ]
