# Generated by Django 2.1.1 on 2019-03-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0028_auto_20190311_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityguideitem',
            name='cover_description',
            field=models.TextField(blank=True, verbose_name='Подпись к изображению'),
        ),
    ]
