# Generated by Django 2.1.1 on 2019-03-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0030_auto_20190312_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='descriptor',
            field=models.TextField(verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='person',
            name='lead',
            field=models.TextField(verbose_name='Лид'),
        ),
    ]
