# Generated by Django 2.1.1 on 2019-03-21 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0031_auto_20190313_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cityguide',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='cityguide',
            name='cover_format',
        ),
    ]
