# Generated by Django 2.1.1 on 2019-04-09 10:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0032_auto_20190321_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='text',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
