# Generated by Django 2.1.1 on 2019-07-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0033_news_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cityguide',
            options={'ordering': ('-id',), 'verbose_name': 'Гид по городу', 'verbose_name_plural': 'Гиды по городу'},
        ),
        migrations.RemoveField(
            model_name='special',
            name='content_author',
        ),
        migrations.RemoveField(
            model_name='special',
            name='cover_author',
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
