# Generated by Django 2.1.1 on 2020-01-13 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0035_auto_20200110_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compilationitem',
            name='compilation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='root.Compilation', verbose_name='Подборка'),
        ),
        migrations.AlterField(
            model_name='compilationitem',
            name='entity',
            field=models.CharField(choices=[('news', 'Новость'), ('event', 'Анонс события'), ('report', 'Репортаж о событии'), ('history', 'Историческая статья'), ('person', 'Статья о жителе Амурска'), ('place', 'Статья о месте')], max_length=255, verbose_name='Сущность'),
        ),
    ]
