# Generated by Django 2.1.1 on 2020-01-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0036_auto_20200113_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='compilationitem',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Состояние'),
        ),
    ]
