# Generated by Django 2.1.1 on 2020-01-17 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0038_compilationitem_publication_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compilationitem',
            name='publication_date',
        ),
    ]
