# Generated by Django 2.1.1 on 2020-01-20 08:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0039_remove_compilationitem_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='publication_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время публикации'),
        ),
    ]
