# Generated by Django 2.1.1 on 2020-01-20 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0040_event_publication_date'),
    ]

    operations = [
        migrations.RunSQL('''
            UPDATE root_event SET publication_date = create_date;
        ''')
    ]
