# Generated by Django 2.1.1 on 2020-07-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0041_auto_20200120_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hide_cover',
            field=models.BooleanField(default=False, verbose_name='Скрывать обложку в мобильных устройствах'),
        ),
        migrations.AddField(
            model_name='history',
            name='hide_cover',
            field=models.BooleanField(default=False, verbose_name='Скрывать обложку в мобильных устройствах'),
        ),
        migrations.AddField(
            model_name='news',
            name='hide_cover',
            field=models.BooleanField(default=False, verbose_name='Скрывать обложку в мобильных устройствах'),
        ),
        migrations.AddField(
            model_name='person',
            name='hide_cover',
            field=models.BooleanField(default=False, verbose_name='Скрывать обложку в мобильных устройствах'),
        ),
        migrations.AddField(
            model_name='place',
            name='hide_cover',
            field=models.BooleanField(default=False, verbose_name='Скрывать обложку в мобильных устройствах'),
        ),
        migrations.AddField(
            model_name='report',
            name='hide_cover',
            field=models.BooleanField(default=False, verbose_name='Скрывать обложку в мобильных устройствах'),
        ),
    ]
