# Generated by Django 2.1.1 on 2018-10-26 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cp_vue', '0007_auto_20181017_1037'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('edit_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Состояние')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('codename', models.CharField(max_length=255, unique=True, verbose_name='Кодовое имя')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События для уведомлений',
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Шаблон')),
                ('codename', models.CharField(max_length=255, unique=True, verbose_name='Кодовое имя')),
            ],
            options={
                'verbose_name': 'Способ отправки',
                'verbose_name_plural': 'Способы отправки',
            },
        ),
        migrations.CreateModel(
            name='HtmlTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('edit_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('text', models.TextField(verbose_name='HTML код')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'HTML шаблон',
                'verbose_name_plural': 'HTML шаблоны',
                'db_table': 'notifications_html_template',
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('edit_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Состояние')),
                ('name', models.CharField(max_length=255, verbose_name='Шаблон')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='Тема письма')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.Action', verbose_name='Событие')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.Channel', verbose_name='Способ отправки')),
            ],
            options={
                'verbose_name': 'Шаблон уведомления',
                'verbose_name_plural': 'Шаблоны уведомлений',
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('edit_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Состояние')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('email', models.EmailField(blank=True, max_length=255, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='Телефон')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.Channel', verbose_name='Способ отправки')),
            ],
            options={
                'verbose_name': 'Получатель',
                'verbose_name_plural': 'Получатели',
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('codename', models.CharField(max_length=255, verbose_name='Кодовое имя')),
                ('construction_type', models.CharField(choices=[('var', 'Переменная'), ('tag', 'Шаблонный тег')], max_length=255, verbose_name='Тип конструкции')),
                ('content_type', models.CharField(blank=True, choices=[('text', 'Текст'), ('link', 'Ссылка'), ('email', 'Email')], max_length=255, verbose_name='Тип содержимого')),
                ('weight', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='notifications.Action', verbose_name='Событие')),
            ],
            options={
                'verbose_name': 'Переменная',
                'verbose_name_plural': 'Переменные',
                'ordering': ['weight'],
            },
        ),
        migrations.AddField(
            model_name='notifications',
            name='recipients',
            field=models.ManyToManyField(blank=True, to='notifications.Recipient', verbose_name='Получатели'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='roles',
            field=models.ManyToManyField(blank=True, to='cp_vue.CpRole', verbose_name='Роли пользователей'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
    ]
