# Generated by Django 2.1.4 on 2018-12-26 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('edit_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Состояние')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('send_date', models.DateTimeField(verbose_name='Дата и время отправки')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема письма')),
                ('content', models.TextField(verbose_name='Содержание письма')),
                ('mailerlite_id', models.BigIntegerField(null=True, verbose_name='Mailer Lite ID')),
                ('sync_date', models.DateTimeField(null=True, verbose_name='Дата и время последней синхронизации')),
                ('comment', models.CharField(blank=True, default='', max_length=255, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Кампания рассылки',
                'verbose_name_plural': 'Кампании рассылки',
            },
        ),
        migrations.CreateModel(
            name='CampaignGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='mailing.Campaign', verbose_name='Кампания')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignSubscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='mailing.Campaign', verbose_name='Кампания')),
            ],
        ),
        migrations.CreateModel(
            name='MailingGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('edit_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Состояние')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('mailerlite_id', models.BigIntegerField(null=True, verbose_name='Mailer Lite ID')),
                ('sync_date', models.DateTimeField(null=True, verbose_name='Дата и время последней синхронизации')),
                ('comment', models.CharField(blank=True, default='', max_length=255, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Группа подписчиков',
                'verbose_name_plural': 'Группы подписчиков',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('edit_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Состояние')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('mailerlite_id', models.BigIntegerField(null=True, verbose_name='Mailer Lite ID')),
                ('sync_date', models.DateTimeField(null=True, verbose_name='Дата и время последней синхронизации')),
                ('comment', models.CharField(blank=True, default='', max_length=255, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Подписчик',
                'verbose_name_plural': 'Подписчики',
            },
        ),
        migrations.CreateModel(
            name='SubscriberGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='mailing.MailingGroup', verbose_name='Группа')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='mailing.Subscriber', verbose_name='Подписчик')),
            ],
        ),
        migrations.AddField(
            model_name='campaignsubscriber',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='mailing.Subscriber', verbose_name='Подписчик'),
        ),
        migrations.AddField(
            model_name='campaigngroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='mailing.MailingGroup', verbose_name='Группа'),
        ),
    ]
