# Generated by Django 2.1.4 on 2018-12-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaigngroup',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='campaigngroup',
            name='group',
        ),
        migrations.RemoveField(
            model_name='campaignsubscriber',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='campaignsubscriber',
            name='subscriber',
        ),
        migrations.RemoveField(
            model_name='subscribergroup',
            name='group',
        ),
        migrations.RemoveField(
            model_name='subscribergroup',
            name='subscriber',
        ),
        migrations.AddField(
            model_name='mailinggroup',
            name='subscribers',
            field=models.ManyToManyField(to='mailing.Subscriber'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.DeleteModel(
            name='CampaignGroup',
        ),
        migrations.DeleteModel(
            name='CampaignSubscriber',
        ),
        migrations.DeleteModel(
            name='SubscriberGroup',
        ),
    ]
