# Generated by Django 2.1.4 on 2018-12-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_auto_20181227_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinggroup',
            name='subscribers',
            field=models.ManyToManyField(related_name='groups', to='mailing.Subscriber'),
        ),
    ]
