# Generated by Django 2.1.4 on 2018-12-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_auto_20181227_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='groups',
            field=models.ManyToManyField(related_name='campaigns', to='mailing.MailingGroup'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='subscribers',
            field=models.ManyToManyField(related_name='campaigns', to='mailing.Subscriber'),
        ),
    ]
