# Generated by Django 2.1.4 on 2019-01-04 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_auto_20181227_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='subscribers',
        ),
        migrations.RemoveField(
            model_name='mailinggroup',
            name='subscribers',
        ),
        migrations.DeleteModel(
            name='Campaign',
        ),
        migrations.DeleteModel(
            name='MailingGroup',
        ),
    ]
