# Generated by Django 2.1.4 on 2019-01-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_auto_20190104_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('edit_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('content', models.TextField(verbose_name='Содержание письма')),
                ('comment', models.CharField(blank=True, default='', max_length=255, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Кампания рассылки',
                'verbose_name_plural': 'Кампании рассылки',
            },
        ),
    ]
