# Generated by Django 2.1.4 on 2018-12-22 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mediafiles', '0003_auto_20181219_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=255, verbose_name='Кодовое название')),
                ('data_type', models.CharField(choices=[('string', 'Короткий текст'), ('text', 'Длинный текст'), ('url', 'Ссылка'), ('mediafile', 'Изображение')], max_length=255, verbose_name='Тип блока')),
                ('content_string', models.CharField(blank=True, max_length=255, verbose_name='Текст')),
                ('content_text', models.TextField(blank=True, verbose_name='Параграф')),
                ('content_url', models.URLField(blank=True, verbose_name='Ссылка')),
                ('content_mediafile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mediafiles.MediaFile', verbose_name='Медиафайл')),
            ],
            options={
                'verbose_name': 'Контент блок',
                'verbose_name_plural': 'Контент блоки',
                'ordering': ['codename'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('edit_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок страницы (title / og:title)')),
                ('meta_description', models.TextField(blank=True, verbose_name='Описание страницы (description / og:description)')),
                ('meta_keywords', models.TextField(blank=True, verbose_name='Ключевые слова, через запятую (keywords)')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('codename', models.CharField(max_length=255, verbose_name='Кодовое название страницы')),
                ('have_content', models.BooleanField(default=False, verbose_name='Имеет контент для редактирования')),
                ('admin_form_config', models.TextField(blank=True, verbose_name='Конфиг формы для админки')),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contentblocks_page_og_image', to='mediafiles.MediaFile', verbose_name='OG-image')),
            ],
            options={
                'verbose_name': 'Статическая страница',
                'verbose_name_plural': 'Статические страницы',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='contentblock',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='contentblocks.Page', verbose_name='Страница'),
        ),
        migrations.AlterUniqueTogether(
            name='contentblock',
            unique_together={('page', 'codename')},
        ),
    ]
