# Generated by Django 2.1.4 on 2019-02-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentblocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='content_bool',
            field=models.BooleanField(blank=True, default=False, verbose_name='Бул'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='data_type',
            field=models.CharField(choices=[('string', 'Короткий текст'), ('text', 'Длинный текст'), ('url', 'Ссылка'), ('mediafile', 'Изображение'), ('bool', 'Бул')], max_length=255, verbose_name='Тип блока'),
        ),
    ]
