# Generated by Django 2.1.1 on 2020-01-13 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0036_auto_20200113_1046'),
        ('contentblocks', '0002_auto_20190218_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='compilation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='root.Compilation', verbose_name='Подборка'),
        ),
    ]
